CREATE TABLE IF NOT EXISTS RECIPE(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	PREP_HOURS INT,
	PREP_MINUTES INT,
	COOK_HOURS INT,
	COOK_MINUTES INT
);

CREATE TABLE IF NOT EXISTS INGREDIENT(
	ID INT AUTO_INCREMENT,
	RECIPE_ID INT,
	INGREDIENT VARCHAR(255),
	MEASUREMENT VARCHAR(50),
	AMOUNT FLOAT
);

CREATE TABLE IF NOT EXISTS STEP(
	ID INT AUTO_INCREMENT,
	RECIPE_ID INT,
	STEP_NUMBER INT,
	STEP VARCHAR(3000)
);

CREATE TABLE IF NOT EXISTS TAG(
	ID INT AUTO_INCREMENT,
	RECIPE_ID INT,
	DESCRIPTION VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS FILTER(
	ID INT AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS FILTER_TAG(
	ID INT AUTO_INCREMENT,
	FILTER_ID INT,
	DESCRIPTION VARCHAR(50),
	GOOD BOOLEAN
);